name: test

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: mstksg/setup-stack@v1
    - name: Setup stack
      run: stack update
